# Generated by Django 4.2 on 2023-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('started', 'started'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='created', max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
